# Generated by Django 3.2.3 on 2021-06-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210624_1321'),
        ('employee', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookinstance', verbose_name='Книга')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.student', verbose_name='Студент')),
            ],
        ),
    ]
