# Generated by Django 3.2.3 on 2021-05-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.country', verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('is_city', models.BooleanField(default=False, verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.region', verbose_name='Область')),
            ],
        ),
    ]
