# Generated by Django 3.2.3 on 2021-05-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.district', verbose_name='Район')),
            ],
        ),
    ]
