# Generated by Django 3.2.3 on 2021-06-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('photo', models.ImageField(upload_to='books/photos', verbose_name='Фотография')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category', verbose_name='Жанр')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.library', verbose_name='Библиотека')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=True, verbose_name='Занят')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.book', verbose_name='Книга')),
            ],
        ),
    ]
