# Generated by Django 3.2.3 on 2021-06-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_bookinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(null=True, upload_to='books/photos', verbose_name='Фотография'),
        ),
    ]
