# Generated by Django 3.2.3 on 2021-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='qr_code',
            field=models.TextField(default=1, verbose_name='QR код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Свободна'),
        ),
    ]
