# Generated by Django 3.2.3 on 2021-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('super_user', 'Администратор'), ('library_admin', 'Администратор библиотеки'), ('employee', 'Сотрудник библиотеки'), ('student', 'Студент')], default='super_user', max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
